name: Donation-Store-Nukkit
author: Donation Store
version: 2.2.3
main: net.donationstore.nukkit.DonationStorePlugin
website: https://donationstore.net
commands:
  ds:
    description: Main command for the Donation Store plugin.
    usage: /ds